/**
 * CRB Table 7-1: Combat Actions
 *
 * Defines all combat actions available in DH2E combat.
 * Each action specifies its cost, group, execution mode, and visibility predicates.
 */

type ActionCost = "half" | "full" | "free" | "reaction" | "varies";
type ActionGroup = "attack" | "movement" | "miscellaneous" | "reaction";
type ExecutionMode = "consume-only" | "attack-pipeline" | "skill-check" | "dialog";
type ActionSubtype = "attack" | "concentration" | "melee" | "ranged" | "movement" | "miscellaneous";

interface CombatAction {
    slug: string;
    label: string;
    labelKey: string;
    descriptionKey: string;
    icon: string;
    actionCost: ActionCost;
    subtypes: ActionSubtype[];
    group: ActionGroup;
    sortOrder: number;
    turnEffect?: string;
    executionMode: ExecutionMode;
    attackOptions?: { fireMode?: string; meleeMode?: string; isCharge?: boolean };
    skillCheck?: { skillName: string; characteristic?: string; modifier?: number };
    visibilityPredicate?: string;
    requiresMelee?: boolean;
    requiresRanged?: boolean;
}

const COMBAT_ACTIONS: CombatAction[] = [
    // ── Attack Actions ────────────────────────────────
    {
        slug: "standard-attack",
        label: "Standard Attack",
        labelKey: "DH2E.CombatAction.StandardAttack.Label",
        descriptionKey: "DH2E.CombatAction.StandardAttack.Desc",
        icon: "fa-solid fa-crosshairs",
        actionCost: "half",
        subtypes: ["attack"],
        group: "attack",
        sortOrder: 10,
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "single" },
    },
    {
        slug: "all-out-attack",
        label: "All Out Attack",
        labelKey: "DH2E.CombatAction.AllOutAttack.Label",
        descriptionKey: "DH2E.CombatAction.AllOutAttack.Desc",
        icon: "fa-solid fa-burst",
        actionCost: "full",
        subtypes: ["attack", "melee"],
        group: "attack",
        sortOrder: 20,
        turnEffect: "all-out-attack",
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "single" },
        requiresMelee: true,
    },
    {
        slug: "called-shot",
        label: "Called Shot",
        labelKey: "DH2E.CombatAction.CalledShot.Label",
        descriptionKey: "DH2E.CombatAction.CalledShot.Desc",
        icon: "fa-solid fa-location-crosshairs",
        actionCost: "full",
        subtypes: ["attack", "concentration"],
        group: "attack",
        sortOrder: 30,
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "single" },
    },
    {
        slug: "charge",
        label: "Charge",
        labelKey: "DH2E.CombatAction.Charge.Label",
        descriptionKey: "DH2E.CombatAction.Charge.Desc",
        icon: "fa-solid fa-person-running",
        actionCost: "full",
        subtypes: ["attack", "melee", "movement"],
        group: "attack",
        sortOrder: 40,
        turnEffect: "charging",
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "single", isCharge: true },
        requiresMelee: true,
    },
    {
        slug: "feint",
        label: "Feint",
        labelKey: "DH2E.CombatAction.Feint.Label",
        descriptionKey: "DH2E.CombatAction.Feint.Desc",
        icon: "fa-solid fa-mask",
        actionCost: "half",
        subtypes: ["attack", "melee"],
        group: "attack",
        sortOrder: 50,
        turnEffect: "feinting",
        executionMode: "skill-check",
        skillCheck: { skillName: "Weapon Skill", characteristic: "ws" },
        requiresMelee: true,
    },
    {
        slug: "semi-auto-burst",
        label: "Semi-Auto Burst",
        labelKey: "DH2E.CombatAction.SemiAutoBurst.Label",
        descriptionKey: "DH2E.CombatAction.SemiAutoBurst.Desc",
        icon: "fa-solid fa-gun",
        actionCost: "half",
        subtypes: ["attack", "ranged"],
        group: "attack",
        sortOrder: 60,
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "semi" },
        requiresRanged: true,
    },
    {
        slug: "full-auto-burst",
        label: "Full Auto Burst",
        labelKey: "DH2E.CombatAction.FullAutoBurst.Label",
        descriptionKey: "DH2E.CombatAction.FullAutoBurst.Desc",
        icon: "fa-solid fa-gun",
        actionCost: "half",
        subtypes: ["attack", "ranged"],
        group: "attack",
        sortOrder: 70,
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "full" },
        requiresRanged: true,
    },
    {
        slug: "stun",
        label: "Stun",
        labelKey: "DH2E.CombatAction.Stun.Label",
        descriptionKey: "DH2E.CombatAction.Stun.Desc",
        icon: "fa-solid fa-hand-fist",
        actionCost: "half",
        subtypes: ["attack", "melee"],
        group: "attack",
        sortOrder: 80,
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "single" },
        requiresMelee: true,
    },
    {
        slug: "knock-down",
        label: "Knock Down",
        labelKey: "DH2E.CombatAction.KnockDown.Label",
        descriptionKey: "DH2E.CombatAction.KnockDown.Desc",
        icon: "fa-solid fa-arrow-down",
        actionCost: "half",
        subtypes: ["attack", "melee"],
        group: "attack",
        sortOrder: 90,
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "single" },
        requiresMelee: true,
    },
    {
        slug: "grapple",
        label: "Grapple",
        labelKey: "DH2E.CombatAction.Grapple.Label",
        descriptionKey: "DH2E.CombatAction.Grapple.Desc",
        icon: "fa-solid fa-hands-holding",
        actionCost: "full",
        subtypes: ["attack", "melee"],
        group: "attack",
        sortOrder: 100,
        executionMode: "dialog",
        requiresMelee: true,
    },
    {
        slug: "manoeuvre",
        label: "Manoeuvre",
        labelKey: "DH2E.CombatAction.Manoeuvre.Label",
        descriptionKey: "DH2E.CombatAction.Manoeuvre.Desc",
        icon: "fa-solid fa-arrows-spin",
        actionCost: "full",
        subtypes: ["attack", "melee"],
        group: "attack",
        sortOrder: 110,
        executionMode: "skill-check",
        skillCheck: { skillName: "Weapon Skill", characteristic: "ws" },
        requiresMelee: true,
    },
    {
        slug: "suppressing-fire",
        label: "Suppressing Fire",
        labelKey: "DH2E.CombatAction.SuppressingFire.Label",
        descriptionKey: "DH2E.CombatAction.SuppressingFire.Desc",
        icon: "fa-solid fa-explosion",
        actionCost: "full",
        subtypes: ["attack", "ranged"],
        group: "attack",
        sortOrder: 120,
        executionMode: "dialog",
        requiresRanged: true,
    },
    {
        slug: "swift-attack",
        label: "Swift Attack",
        labelKey: "DH2E.CombatAction.SwiftAttack.Label",
        descriptionKey: "DH2E.CombatAction.SwiftAttack.Desc",
        icon: "fa-solid fa-wind",
        actionCost: "full",
        subtypes: ["attack", "melee"],
        group: "attack",
        sortOrder: 130,
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "single", meleeMode: "swift" },
        visibilityPredicate: "talent:swift-attack",
        requiresMelee: true,
    },
    {
        slug: "lightning-attack",
        label: "Lightning Attack",
        labelKey: "DH2E.CombatAction.LightningAttack.Label",
        descriptionKey: "DH2E.CombatAction.LightningAttack.Desc",
        icon: "fa-solid fa-bolt",
        actionCost: "full",
        subtypes: ["attack", "melee"],
        group: "attack",
        sortOrder: 140,
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "single", meleeMode: "lightning" },
        visibilityPredicate: "talent:lightning-attack",
        requiresMelee: true,
    },

    // ── Movement Actions ──────────────────────────────
    {
        slug: "move-half",
        label: "Half Move",
        labelKey: "DH2E.CombatAction.HalfMove.Label",
        descriptionKey: "DH2E.CombatAction.HalfMove.Desc",
        icon: "fa-solid fa-shoe-prints",
        actionCost: "half",
        subtypes: ["movement"],
        group: "movement",
        sortOrder: 200,
        executionMode: "consume-only",
    },
    {
        slug: "move-full",
        label: "Full Move",
        labelKey: "DH2E.CombatAction.FullMove.Label",
        descriptionKey: "DH2E.CombatAction.FullMove.Desc",
        icon: "fa-solid fa-person-walking",
        actionCost: "full",
        subtypes: ["movement"],
        group: "movement",
        sortOrder: 210,
        executionMode: "consume-only",
    },
    {
        slug: "run",
        label: "Run",
        labelKey: "DH2E.CombatAction.Run.Label",
        descriptionKey: "DH2E.CombatAction.Run.Desc",
        icon: "fa-solid fa-bolt-lightning",
        actionCost: "full",
        subtypes: ["movement"],
        group: "movement",
        sortOrder: 220,
        turnEffect: "running",
        executionMode: "consume-only",
    },
    {
        slug: "charge",
        label: "Charge",
        labelKey: "DH2E.CombatAction.Charge.Label",
        descriptionKey: "DH2E.CombatAction.Charge.Desc",
        icon: "fa-solid fa-person-running",
        actionCost: "full",
        subtypes: ["attack", "melee", "movement"],
        group: "movement",
        sortOrder: 230,
        turnEffect: "charging",
        executionMode: "attack-pipeline",
        attackOptions: { fireMode: "single", isCharge: true },
        requiresMelee: true,
    },
    {
        slug: "tactical-advance",
        label: "Tactical Advance",
        labelKey: "DH2E.CombatAction.TacticalAdvance.Label",
        descriptionKey: "DH2E.CombatAction.TacticalAdvance.Desc",
        icon: "fa-solid fa-shield-halved",
        actionCost: "full",
        subtypes: ["movement", "concentration"],
        group: "movement",
        sortOrder: 240,
        executionMode: "consume-only",
    },
    {
        slug: "disengage",
        label: "Disengage",
        labelKey: "DH2E.CombatAction.Disengage.Label",
        descriptionKey: "DH2E.CombatAction.Disengage.Desc",
        icon: "fa-solid fa-right-from-bracket",
        actionCost: "full",
        subtypes: ["movement"],
        group: "movement",
        sortOrder: 250,
        executionMode: "consume-only",
    },
    {
        slug: "stand-mount",
        label: "Stand / Mount",
        labelKey: "DH2E.CombatAction.StandMount.Label",
        descriptionKey: "DH2E.CombatAction.StandMount.Desc",
        icon: "fa-solid fa-arrow-up",
        actionCost: "half",
        subtypes: ["movement"],
        group: "movement",
        sortOrder: 260,
        executionMode: "consume-only",
    },

    // ── Miscellaneous Actions ─────────────────────────
    {
        slug: "aim-half",
        label: "Aim (Half)",
        labelKey: "DH2E.CombatAction.AimHalf.Label",
        descriptionKey: "DH2E.CombatAction.AimHalf.Desc",
        icon: "fa-solid fa-bullseye",
        actionCost: "half",
        subtypes: ["concentration"],
        group: "miscellaneous",
        sortOrder: 300,
        turnEffect: "aiming",
        executionMode: "consume-only",
    },
    {
        slug: "aim-full",
        label: "Aim (Full)",
        labelKey: "DH2E.CombatAction.AimFull.Label",
        descriptionKey: "DH2E.CombatAction.AimFull.Desc",
        icon: "fa-solid fa-bullseye",
        actionCost: "full",
        subtypes: ["concentration"],
        group: "miscellaneous",
        sortOrder: 310,
        turnEffect: "aiming-full",
        executionMode: "consume-only",
    },
    {
        slug: "brace-heavy-weapon",
        label: "Brace Heavy Weapon",
        labelKey: "DH2E.CombatAction.BraceHeavyWeapon.Label",
        descriptionKey: "DH2E.CombatAction.BraceHeavyWeapon.Desc",
        icon: "fa-solid fa-mountain",
        actionCost: "half",
        subtypes: ["miscellaneous"],
        group: "miscellaneous",
        sortOrder: 320,
        executionMode: "consume-only",
    },
    {
        slug: "focus-power",
        label: "Focus Power",
        labelKey: "DH2E.CombatAction.FocusPower.Label",
        descriptionKey: "DH2E.CombatAction.FocusPower.Desc",
        icon: "fa-solid fa-hat-wizard",
        actionCost: "varies",
        subtypes: ["concentration"],
        group: "miscellaneous",
        sortOrder: 330,
        executionMode: "dialog",
        visibilityPredicate: "talent:psy-rating",
    },
    {
        slug: "guard",
        label: "Guard",
        labelKey: "DH2E.CombatAction.Guard.Label",
        descriptionKey: "DH2E.CombatAction.Guard.Desc",
        icon: "fa-solid fa-shield",
        actionCost: "half",
        subtypes: ["concentration", "melee"],
        group: "miscellaneous",
        sortOrder: 340,
        turnEffect: "guarding",
        executionMode: "consume-only",
    },
    {
        slug: "overwatch",
        label: "Overwatch",
        labelKey: "DH2E.CombatAction.Overwatch.Label",
        descriptionKey: "DH2E.CombatAction.Overwatch.Desc",
        icon: "fa-solid fa-eye",
        actionCost: "half",
        subtypes: ["concentration", "ranged"],
        group: "miscellaneous",
        sortOrder: 350,
        turnEffect: "overwatch",
        executionMode: "dialog",
        requiresRanged: true,
    },
    {
        slug: "ready",
        label: "Ready",
        labelKey: "DH2E.CombatAction.Ready.Label",
        descriptionKey: "DH2E.CombatAction.Ready.Desc",
        icon: "fa-solid fa-hand",
        actionCost: "half",
        subtypes: ["miscellaneous"],
        group: "miscellaneous",
        sortOrder: 360,
        executionMode: "consume-only",
    },
    {
        slug: "reload",
        label: "Reload",
        labelKey: "DH2E.CombatAction.Reload.Label",
        descriptionKey: "DH2E.CombatAction.Reload.Desc",
        icon: "fa-solid fa-arrows-rotate",
        actionCost: "varies",
        subtypes: ["miscellaneous"],
        group: "miscellaneous",
        sortOrder: 370,
        executionMode: "consume-only",
    },
    {
        slug: "use-skill",
        label: "Use a Skill",
        labelKey: "DH2E.CombatAction.UseSkill.Label",
        descriptionKey: "DH2E.CombatAction.UseSkill.Desc",
        icon: "fa-solid fa-wrench",
        actionCost: "varies",
        subtypes: ["miscellaneous"],
        group: "miscellaneous",
        sortOrder: 380,
        executionMode: "consume-only",
    },

    // ── Free Actions ──────────────────────────────────
    {
        slug: "drop-prone",
        label: "Drop Prone",
        labelKey: "DH2E.CombatAction.DropProne.Label",
        descriptionKey: "DH2E.CombatAction.DropProne.Desc",
        icon: "fa-solid fa-person-arrow-down-to-line",
        actionCost: "free",
        subtypes: ["movement"],
        group: "miscellaneous",
        sortOrder: 400,
        executionMode: "consume-only",
    },
    {
        slug: "drop-weapon",
        label: "Drop Weapon",
        labelKey: "DH2E.CombatAction.DropWeapon.Label",
        descriptionKey: "DH2E.CombatAction.DropWeapon.Desc",
        icon: "fa-solid fa-hand-holding",
        actionCost: "free",
        subtypes: ["miscellaneous"],
        group: "miscellaneous",
        sortOrder: 410,
        executionMode: "consume-only",
    },
    {
        slug: "speak",
        label: "Speak",
        labelKey: "DH2E.CombatAction.Speak.Label",
        descriptionKey: "DH2E.CombatAction.Speak.Desc",
        icon: "fa-solid fa-comment",
        actionCost: "free",
        subtypes: ["miscellaneous"],
        group: "miscellaneous",
        sortOrder: 420,
        executionMode: "consume-only",
    },

    // ── Reactions ─────────────────────────────────────
    {
        slug: "dodge",
        label: "Dodge",
        labelKey: "DH2E.CombatAction.Dodge.Label",
        descriptionKey: "DH2E.CombatAction.Dodge.Desc",
        icon: "fa-solid fa-person-falling",
        actionCost: "reaction",
        subtypes: ["movement"],
        group: "reaction",
        sortOrder: 500,
        executionMode: "skill-check",
        skillCheck: { skillName: "Dodge", characteristic: "ag" },
    },
    {
        slug: "parry",
        label: "Parry",
        labelKey: "DH2E.CombatAction.Parry.Label",
        descriptionKey: "DH2E.CombatAction.Parry.Desc",
        icon: "fa-solid fa-shield-halved",
        actionCost: "reaction",
        subtypes: ["melee"],
        group: "reaction",
        sortOrder: 510,
        executionMode: "skill-check",
        skillCheck: { skillName: "Parry", characteristic: "ws" },
    },
];

// Remove duplicate charge (exists in both attack and movement groups — keep only attack group)
const COMBAT_ACTIONS_DEDUPED = COMBAT_ACTIONS.filter((a, i) =>
    COMBAT_ACTIONS.findIndex((b) => b.slug === a.slug) === i,
);

/** O(1) lookup by slug */
const COMBAT_ACTIONS_BY_SLUG: Record<string, CombatAction> = {};
for (const action of COMBAT_ACTIONS_DEDUPED) {
    COMBAT_ACTIONS_BY_SLUG[action.slug] = action;
}

export { COMBAT_ACTIONS, COMBAT_ACTIONS_DEDUPED, COMBAT_ACTIONS_BY_SLUG };
export type { CombatAction, ActionCost, ActionGroup, ExecutionMode, ActionSubtype };
